# frozen_string_literal: true

# key_codes.rb: Key name to curses key code mappings for ProfanityFE.

# Key name to curses key code mappings

KEY_NAME = {
  'ctrl+a'        => 1,
  'ctrl+b'        => 2,
  #	'ctrl+c'    => 3,
  'ctrl+d'        => 4,
  'ctrl+e'        => 5,
  'ctrl+f'        => 6,
  'ctrl+g'        => 7,
  'ctrl+h'        => 8,
  'win_backspace' => 8,
  'ctrl+i'        => 9,
  'tab'           => 9,
  'ctrl+j'        => 10,
  'enter'         => 10,
  'ctrl+k'        => 11,
  'ctrl+l'        => 12,
  'return'        => 13,
  'ctrl+m'        => 13,
  'ctrl+n'        => 14,
  'ctrl+o'        => 15,
  'ctrl+p'        => 16,
  #	'ctrl+q'    => 17,
  'ctrl+r'        => 18,
  #	'ctrl+s'    => 19,
  'ctrl+t'        => 20,
  'ctrl+u'        => 21,
  'ctrl+v'        => 22,
  'ctrl+w'        => 23,
  'ctrl+x'        => 24,
  'ctrl+y'        => 25,
  #	'ctrl+z'    => 26,
  'alt'           => 27,
  'escape'        => 27,
  'ctrl+?'        => 127,
  'down'          => 258,
  'up'            => 259,
  'left'          => 260,
  'right'         => 261,
  'home'          => 262,
  'backspace'     => 263,
  'f1'            => 265,
  'f2'            => 266,
  'f3'            => 267,
  'f4'            => 268,
  'f5'            => 269,
  'f6'            => 270,
  'f7'            => 271,
  'f8'            => 272,
  'f9'            => 273,
  'f10'           => 274,
  'f11'           => 275,
  'f12'           => 276,
  'delete'        => 330,
  'insert'        => 331,
  'page_down'     => 338,
  'page_up'       => 339,
  'win_end'       => 358,
  'end'           => 360,
  'resize'        => 410,
  'num_7'         => 449,
  'num_8'         => 450,
  'num_9'         => 451,
  'num_4'         => 452,
  'num_5'         => 453,
  'num_6'         => 454,
  'num_1'         => 455,
  'num_2'         => 456,
  'num_3'         => 457,
  'num_enter'     => 459,
  'ctrl+delete'   => 513,
  'alt+down'      => 517,
  'ctrl+down'     => 519,
  'alt+left'      => 537,
  'ctrl+left'     => 539,
  'alt+page_down' => 542,
  'alt+page_up'   => 547,
  'alt+right'     => 552,
  'ctrl+right'    => 554,
  'alt+up'        => 558,
  'shift+down'    => 336,
  'shift+up'      => 337,
  'ctrl+up'       => 560,
  # Alt+number for tab switching: the terminal sends ESC then the digit.
  # Curses getch returns a printable key as a one-character String, not its
  # Integer code, so the digit must be a String here to ever match.
  'alt+1'         => [27, '1'],
  'alt+2'         => [27, '2'],
  'alt+3'         => [27, '3'],
  'alt+4'         => [27, '4'],
  'alt+5'         => [27, '5']
}.freeze
