name: Rubocop
on: 
  push:
    branches:
      - main
    paths:
      - "**/*.rb"
      - "*.rb"
  pull_request:
    paths:
      - "**/*.rb"
      - "*.rb"
jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: 'gtk:vscode:profanity'
    name: Run Rubocop on Ruby
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.2
        with:
          fetch-depth: 0
      
      - uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
        with:
          bundler-cache: true

      - name: Rubocop
        run: |
          bundle exec rubocop
