name: Valid Ruby Syntax
on: 
  push:
    branches:
      - main
    paths:
      - "**/*.rb"
      - "*.rb"
  pull_request:
    paths:
      - "**/*.rb"
      - "*.rb"

jobs:
  check_syntax:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: 'gtk:vscode:profanity'
    name: Run tests on Ruby
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.2
        with:
          fetch-depth: 0
          
      - name: Get changed files
        id: changed-files
        uses: step-security/changed-files@95b56dadb92a30ca9036f16423fd3c088a71ee94 # v46.0.5
        with:
          files: |
            **/*.rb
            *.rb

      - uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
        with:
          bundler-cache: true
          
      - name: Run Ruby syntax check on changed scripts
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ruby -c $file
          done
